---
run:
  timeout: "5m"
  skip-dirs:
    - "proto"
output:
  sort-results: true
linters-settings:
  goimports:
    local-prefixes: "github.com/authzed/authzed-go"
linters:
  enable:
    - "deadcode"
    - "errcheck"
    - "gofumpt"
    - "goimports"
    - "gosimple"
    - "govet"
    - "ineffassign"
    - "revive"
    - "rowserrcheck"
    - "staticcheck"
    - "structcheck"
    - "typecheck"
    - "unused"
    - "varcheck"
