name: "build"
on:
  push:
    branches:
    - "!dependabot/*"
    - "*"
  pull_request:
    branches:
    - "*"
jobs:
  lint: 
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-go@v2"
      with:
        go-version: ^1.16
    - name: "go fmt"
      run: |
        GOFMT_OUTPUT="$(gofmt -l `find ./ -name '*.go' | grep -v vendor` 2>&1)"

        if [ -n "$GOFMT_OUTPUT" ]; then
          echo "All the following files are not correctly formatted"
          echo "${GOFMT_OUTPUT}"
          exit 1
        fi
    - name: "go imports"
      run: |
        exec 5>&1
        GOIMPORTS_OUTPUT="$(goimports -l -w `find ./ -name '*.go' | grep -v vendor` | tee /dev/fd/5)"

        if [ -n "$GOIMPORTS_OUTPUT" ]; then
          echo "All following has imports not properly ordered"
          echo "${GOIMPORTS_OUTPUT}"

          exit 1
        fi
    - name: "go mod tidy"
      run: |
        GO_MOD_OUPUT="$(go mod tidy -v 2>&1)"

        if [[ $GO_MOD_OUPUT == *"unused"* ]]; then
          echo "${GO_MOD_OUPUT}"
          exit 1
        fi
    - uses: golangci/golangci-lint-action@v2

  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-go@v2"
      with:
        go-version: ^1.16
    - uses: "authzed/action-testserver@v3"
    - name: "go test"
      run: "go test -tags integration ./..."

  protobuf:
    name: "Generate Protobufs"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-go@v2"
      with:
        go-version: ^1.16
    - name: "Install Go Protobuf plugins"
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
        go install github.com/envoyproxy/protoc-gen-validate@v0.6.1
    - uses: "bufbuild/buf-setup-action@v0.1.0"
      with:
        version: "0.43.2"
    - name: "Generate & Diff Protos"
      run: |
        ./buf.gen.yaml
        bash -c '[ $(git status --porcelain | tee /dev/fd/2 | wc -c) -eq 0 ]'
