---
name: "build"
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "!dependabot/*"
      - "*"
jobs:
  lint:
    name: "Lint Go"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v3"
        with:
          go-version: "~1.18"
      - uses: "authzed/actions/gofumpt@main"
      - uses: "authzed/actions/go-mod-tidy@main"
      - uses: "authzed/actions/go-generate@main"
      - uses: "authzed/actions/golangci-lint@main"

  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v3"
        with:
          go-version: "~1.18"
      - uses: "authzed/action-spicedb@v1"
      - uses: "authzed/actions/go-test@main"
        with:
          tags: "integration"
          race: "false"

  protobuf:
    name: "Generate Protobufs"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/setup-go@v2"
        with:
          go-version: "^1.16"
      - name: "Install local Go Protobuf plugins"
        run: "go install github.com/envoyproxy/protoc-gen-validate@v0.6.1"
      - uses: "actions/checkout@v2"
      - uses: "bufbuild/buf-setup-action@v0.6.0"
        with:
          version: "1.0.0-rc12"
      - name: "Generate & Diff Protos"
        run: "./buf.gen.yaml && git diff --text && bash -c '[ $(git status --porcelain | tee /dev/fd/2 | wc -c) -eq 0 ]'"
