---
name: "Build & Test"
on: # yamllint disable-line rule:truthy
  - "push"
  - "pull_request"
jobs:
  test:
    name: "Run Integration Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v3"
        with:
          go-version: "~1.18"
      - uses: "authzed/action-spicedb@v1"
      - uses: "authzed/actions/go-test@main"
        with:
          tags: "integration"
          race: "false"

  protobuf:
    name: "Generate Protobufs"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v3"
        with:
          go-version: "~1.18"
      - name: "Install Go Tools"
        run: "./install-tools.sh"
      - uses: "authzed/actions/buf-generate@main"
