---
name: "Lint"
on: # yamllint disable-line rule:truthy
  - "push"
  - "pull_request"
jobs:
  go-lint:
    name: "Lint Go"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v3"
        with:
          go-version: "~1.18"
      - uses: "authzed/actions/gofumpt@main"
      - uses: "authzed/actions/go-mod-tidy@main"
      - uses: "authzed/actions/go-generate@main"
      - uses: "authzed/actions/golangci-lint@main"
  trivy:
    name: "Analyze with Trivy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Run Trivy vulnerability scanner"
        uses: "aquasecurity/trivy-action@master"
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL"
      - name: "Upload Trivy scan results to GitHub Security tab"
        uses: "github/codeql-action/upload-sarif@v2"
        with:
          sarif_file: 'trivy-results.sarif'
